//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InitialProject.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InitialProject.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        internal static string _in {
            get {
                return ResourceManager.GetString("in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        internal static string Activated {
            get {
                return ResourceManager.GetString("Activated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADD.
        /// </summary>
        internal static string ADDBUTTON {
            get {
                return ResourceManager.GetString("ADDBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Checkpoints.
        /// </summary>
        internal static string AddCheckpoints {
            get {
                return ResourceManager.GetString("AddCheckpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add date and time.
        /// </summary>
        internal static string AddDateAndTime {
            get {
                return ResourceManager.GetString("AddDateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tour by language.
        /// </summary>
        internal static string AddTourByLanguageView {
            get {
                return ResourceManager.GetString("AddTourByLanguageView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tour by location.
        /// </summary>
        internal static string AddTourByLocation {
            get {
                return ResourceManager.GetString("AddTourByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add tour .
        /// </summary>
        internal static string AddTourView {
            get {
                return ResourceManager.GetString("AddTourView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age statistics.
        /// </summary>
        internal static string AgeStatistics {
            get {
                return ResourceManager.GetString("AgeStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to quit a job?.
        /// </summary>
        internal static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already exitsts tour at this time.
        /// </summary>
        internal static string AlreadyExitsTourAtThisTime {
            get {
                return ResourceManager.GetString("AlreadyExitsTourAtThisTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel tour:.
        /// </summary>
        internal static string AreYouSure {
            get {
                return ResourceManager.GetString("AreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 date is required.
        /// </summary>
        internal static string AtLeast1DateIsRequired {
            get {
                return ResourceManager.GetString("AtLeast1DateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 1 image is required.
        /// </summary>
        internal static string AtLeast1ImageIsRequired {
            get {
                return ResourceManager.GetString("AtLeast1ImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least 2 checkpoints are required.
        /// </summary>
        internal static string AtLeast2CheckpointsAreRequired {
            get {
                return ResourceManager.GetString("AtLeast2CheckpointsAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you no longer want to be part of our system press button DISMISSAL. After that you would not be able to use system as guide..
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before regular end.
        /// </summary>
        internal static string BeforeRegularEnd {
            get {
                return ResourceManager.GetString("BeforeRegularEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Between 18 and 50.
        /// </summary>
        internal static string Between18and {
            get {
                return ResourceManager.GetString("Between18and", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        internal static string CANCELBUTTON {
            get {
                return ResourceManager.GetString("CANCELBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL TOUR.
        /// </summary>
        internal static string CancelTour {
            get {
                return ResourceManager.GetString("CancelTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour cancelation.
        /// </summary>
        internal static string CancelView {
            get {
                return ResourceManager.GetString("CancelView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        internal static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHANGE VALIDITY.
        /// </summary>
        internal static string CHANGEVALIDITY {
            get {
                return ResourceManager.GetString("CHANGEVALIDITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checked.
        /// </summary>
        internal static string Checked {
            get {
                return ResourceManager.GetString("Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkpoint name.
        /// </summary>
        internal static string CheckpointName {
            get {
                return ResourceManager.GetString("CheckpointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Checkpoint:.
        /// </summary>
        internal static string Checkpoints {
            get {
                return ResourceManager.GetString("Checkpoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose:.
        /// </summary>
        internal static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex.
        /// </summary>
        internal static string Complex {
            get {
                return ResourceManager.GetString("Complex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMPLEX REQUESTS.
        /// </summary>
        internal static string ComplexRequest {
            get {
                return ResourceManager.GetString("ComplexRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONFIRM.
        /// </summary>
        internal static string CONFIRM {
            get {
                return ResourceManager.GetString("CONFIRM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        internal static string CREATE {
            get {
                return ResourceManager.GetString("CREATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        internal static string CREATEBUTTON {
            get {
                return ResourceManager.GetString("CREATEBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tour.
        /// </summary>
        internal static string Createtour {
            get {
                return ResourceManager.GetString("Createtour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create tour from request.
        /// </summary>
        internal static string CreateTourFromRequest {
            get {
                return ResourceManager.GetString("CreateTourFromRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ⟟ Current checkpoint:.
        /// </summary>
        internal static string CurrentCheckPoint {
            get {
                return ResourceManager.GetString("CurrentCheckPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DARK.
        /// </summary>
        internal static string DARK {
            get {
                return ResourceManager.GetString("DARK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        internal static string DELETE {
            get {
                return ResourceManager.GetString("DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DESCRIPTION.
        /// </summary>
        internal static string DESCRIPTIONBUTTON {
            get {
                return ResourceManager.GetString("DESCRIPTIONBUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILS.
        /// </summary>
        internal static string DETAILS {
            get {
                return ResourceManager.GetString("DETAILS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string DetailsHeader {
            get {
                return ResourceManager.GetString("DetailsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DISMISSAL.
        /// </summary>
        internal static string dismissal {
            get {
                return ResourceManager.GetString("dismissal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not exists request for that location!.
        /// </summary>
        internal static string Donotexistsforlocation {
            get {
                return ResourceManager.GetString("Donotexistsforlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do not exists request for that language!.
        /// </summary>
        internal static string Donotexistsforthatlanguage {
            get {
                return ResourceManager.GetString("Donotexistsforthatlanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration of tour in hours.
        /// </summary>
        internal static string DurationInHours {
            get {
                return ResourceManager.GetString("DurationInHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End date.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        internal static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter point name.
        /// </summary>
        internal static string EnterPointName {
            get {
                return ResourceManager.GetString("EnterPointName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished tour details.
        /// </summary>
        internal static string FinishedTourDetails {
            get {
                return ResourceManager.GetString("FinishedTourDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished tours:.
        /// </summary>
        internal static string FinishedTours {
            get {
                return ResourceManager.GetString("FinishedTours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🏁 FINISH TOUR.
        /// </summary>
        internal static string FINISHTOUR {
            get {
                return ResourceManager.GetString("FINISHTOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GENERATE REPORT.
        /// </summary>
        internal static string GENERATEREPORT {
            get {
                return ResourceManager.GetString("GENERATEREPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grades.
        /// </summary>
        internal static string Grades {
            get {
                return ResourceManager.GetString("Grades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest.
        /// </summary>
        internal static string Guest {
            get {
                return ResourceManager.GetString("Guest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Confirmed guests presence from reservations of:.
        /// </summary>
        internal static string GuestsReservations {
            get {
                return ResourceManager.GetString("GuestsReservations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest was on points:.
        /// </summary>
        internal static string GuestWasOnPoints_ {
            get {
                return ResourceManager.GetString("GuestWasOnPoints:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide already has tour at this time!.
        /// </summary>
        internal static string GUIDEALREADYHASTOUR {
            get {
                return ResourceManager.GetString("GUIDEALREADYHASTOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guide&apos;s knowledge.
        /// </summary>
        internal static string Guidesknowledge {
            get {
                return ResourceManager.GetString("Guidesknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GuideWindow.
        /// </summary>
        internal static string GuideWindow {
            get {
                return ResourceManager.GetString("GuideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HOME PAGE.
        /// </summary>
        internal static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you want to finish tour.
        /// </summary>
        internal static string ifYouWantToFinishTour {
            get {
                return ResourceManager.GetString("ifYouWantToFinishTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images.
        /// </summary>
        internal static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images of tour.
        /// </summary>
        internal static string ImagesOfTour {
            get {
                return ResourceManager.GetString("ImagesOfTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location in last year.
        /// </summary>
        internal static string InLastYear {
            get {
                return ResourceManager.GetString("InLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language in last year.
        /// </summary>
        internal static string InLastYearLanguage {
            get {
                return ResourceManager.GetString("InLastYearLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input year:.
        /// </summary>
        internal static string InputYear {
            get {
                return ResourceManager.GetString("InputYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input year first.
        /// </summary>
        internal static string InputYearFirst {
            get {
                return ResourceManager.GetString("InputYearFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language in last year.
        /// </summary>
        internal static string LanguageInLastYear {
            get {
                return ResourceManager.GetString("LanguageInLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Knowledge of language.
        /// </summary>
        internal static string LanguageKnowledge {
            get {
                return ResourceManager.GetString("LanguageKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to language in last year.
        /// </summary>
        internal static string langugaeinlastyear {
            get {
                return ResourceManager.GetString("langugaeinlastyear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LIGHT.
        /// </summary>
        internal static string LIGHT {
            get {
                return ResourceManager.GetString("LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of ordinary requests for selected complex request.
        /// </summary>
        internal static string ListodOrdinaryRequests {
            get {
                return ResourceManager.GetString("ListodOrdinaryRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List od checkpoints for chosen tour:.
        /// </summary>
        internal static string ListOfCheckpointsForChosenTour {
            get {
                return ResourceManager.GetString("ListOfCheckpointsForChosenTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of complex requests.
        /// </summary>
        internal static string ListOfComplexRequests {
            get {
                return ResourceManager.GetString("ListOfComplexRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to location in last year.
        /// </summary>
        internal static string LocationInLastYear {
            get {
                return ResourceManager.GetString("LocationInLastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        internal static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTHLY.
        /// </summary>
        internal static string MONTHLY {
            get {
                return ResourceManager.GetString("MONTHLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly statistic for requests on language.
        /// </summary>
        internal static string MonthlyLanguage {
            get {
                return ResourceManager.GetString("MonthlyLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly statistic for requests on location.
        /// </summary>
        internal static string MonthlyLocation {
            get {
                return ResourceManager.GetString("MonthlyLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MONTHLY REQUESTS STATISTIC.
        /// </summary>
        internal static string MONTHLYREQUESTSSTATISTIC {
            get {
                return ResourceManager.GetString("MONTHLYREQUESTSSTATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly requests statistic by language.
        /// </summary>
        internal static string MonthlyStatistic {
            get {
                return ResourceManager.GetString("MonthlyStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MY PROFILE.
        /// </summary>
        internal static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New requests:.
        /// </summary>
        internal static string NewRequests {
            get {
                return ResourceManager.GetString("NewRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New reviews:.
        /// </summary>
        internal static string NewReviews {
            get {
                return ResourceManager.GetString("NewReviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Number of presence guests:.
        /// </summary>
        internal static string NumberOfGuests {
            get {
                return ResourceManager.GetString("NumberOfGuests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of requests.
        /// </summary>
        internal static string NumberRequests {
            get {
                return ResourceManager.GetString("NumberRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the most wanted.
        /// </summary>
        internal static string Onthemostwanted {
            get {
                return ResourceManager.GetString("Onthemostwanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        internal static string Order {
            get {
                return ResourceManager.GetString("Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over 50.
        /// </summary>
        internal static string Over50 {
            get {
                return ResourceManager.GetString("Over50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select city.
        /// </summary>
        internal static string PleaseSelectCity {
            get {
                return ResourceManager.GetString("PleaseSelectCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press FINISH TOUR.
        /// </summary>
        internal static string PressFINISHTOUR {
            get {
                return ResourceManager.GetString("PressFINISHTOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string Regular {
            get {
                return ResourceManager.GetString("Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGULAR TOUR REQUESTS.
        /// </summary>
        internal static string REGULARTOURREQUESTS {
            get {
                return ResourceManager.GetString("REGULARTOURREQUESTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regulary tour request overview.
        /// </summary>
        internal static string RegularyRequestOverview {
            get {
                return ResourceManager.GetString("RegularyRequestOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests with waiting status.
        /// </summary>
        internal static string RequestsList {
            get {
                return ResourceManager.GetString("RequestsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests yearly statistic.
        /// </summary>
        internal static string RequestsStatisticYearly {
            get {
                return ResourceManager.GetString("RequestsStatisticYearly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly requests statistic by location.
        /// </summary>
        internal static string RequestStatisticMonthlyLocatiovView {
            get {
                return ResourceManager.GetString("RequestStatisticMonthlyLocatiovView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review.
        /// </summary>
        internal static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEW.
        /// </summary>
        internal static string ReviewButton {
            get {
                return ResourceManager.GetString("ReviewButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review from:.
        /// </summary>
        internal static string ReviewFrom {
            get {
                return ResourceManager.GetString("ReviewFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviews.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REVIEWS.
        /// </summary>
        internal static string REVIEWSHEADER {
            get {
                return ResourceManager.GetString("REVIEWSHEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filters:.
        /// </summary>
        internal static string SelectFilters {
            get {
                return ResourceManager.GetString("SelectFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected time point is already taken.
        /// </summary>
        internal static string SelectOtherTime {
            get {
                return ResourceManager.GetString("SelectOtherTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔎 SHOW.
        /// </summary>
        internal static string SHOW {
            get {
                return ResourceManager.GetString("SHOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to START.
        /// </summary>
        internal static string START {
            get {
                return ResourceManager.GetString("START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistics.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on the most wanted.
        /// </summary>
        internal static string themost {
            get {
                return ResourceManager.GetString("themost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most visited tour.
        /// </summary>
        internal static string TheMostVistedTour {
            get {
                return ResourceManager.GetString("TheMostVistedTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for chosen year.
        /// </summary>
        internal static string TheMostVistedTourYear {
            get {
                return ResourceManager.GetString("TheMostVistedTourYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most wanted.
        /// </summary>
        internal static string Themostwanted {
            get {
                return ResourceManager.GetString("Themostwanted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most wanted.
        /// </summary>
        internal static string TheMostWantedLocation {
            get {
                return ResourceManager.GetString("TheMostWantedLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no tours for this year.
        /// </summary>
        internal static string ThereAreNoToursForThisYear {
            get {
                return ResourceManager.GetString("ThereAreNoToursForThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This filed is required.
        /// </summary>
        internal static string ThisFieldIsRequired {
            get {
                return ResourceManager.GetString("ThisFieldIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tour is finished!.
        /// </summary>
        internal static string ThisTourIsFinished {
            get {
                return ResourceManager.GetString("ThisTourIsFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today&apos;s tours:.
        /// </summary>
        internal static string Todays {
            get {
                return ResourceManager.GetString("Todays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total attendance.
        /// </summary>
        internal static string TotalAttendance {
            get {
                return ResourceManager.GetString("TotalAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour is successfully created!.
        /// </summary>
        internal static string TOURCREATED {
            get {
                return ResourceManager.GetString("TOURCREATED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour Details.
        /// </summary>
        internal static string TourDetails {
            get {
                return ResourceManager.GetString("TourDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOUR FORM.
        /// </summary>
        internal static string TourForm {
            get {
                return ResourceManager.GetString("TourForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour instance reviews overview.
        /// </summary>
        internal static string TourInstanceReviewView {
            get {
                return ResourceManager.GetString("TourInstanceReviewView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interestigness of tour.
        /// </summary>
        internal static string TourInterestigness {
            get {
                return ResourceManager.GetString("TourInterestigness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour name.
        /// </summary>
        internal static string TourName {
            get {
                return ResourceManager.GetString("TourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        internal static string Tours {
            get {
                return ResourceManager.GetString("Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TOUR STATISTIC.
        /// </summary>
        internal static string TOURSTATISTIC {
            get {
                return ResourceManager.GetString("TOURSTATISTIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour statistics.
        /// </summary>
        internal static string TourStatistics {
            get {
                return ResourceManager.GetString("TourStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Under 18.
        /// </summary>
        internal static string Under18 {
            get {
                return ResourceManager.GetString("Under18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity.
        /// </summary>
        internal static string Validity {
            get {
                return ResourceManager.GetString("Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity is changed!.
        /// </summary>
        internal static string ValidityChanged {
            get {
                return ResourceManager.GetString("ValidityChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIEW.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voucher statistics.
        /// </summary>
        internal static string VoucherStatistics {
            get {
                return ResourceManager.GetString("VoucherStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Without vouchers.
        /// </summary>
        internal static string WithoutVouchers {
            get {
                return ResourceManager.GetString("WithoutVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With vouchers.
        /// </summary>
        internal static string WithVouchers {
            get {
                return ResourceManager.GetString("WithVouchers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEARLY REQUEST STATISTIC.
        /// </summary>
        internal static string YEARLYREQUESTSSTATISTC {
            get {
                return ResourceManager.GetString("YEARLYREQUESTSSTATISTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
